version: '3.8'

services:
  joblisting-app:
    image: joblisting_app
    build:
      context: .
      dockerfile: Dockerfile
    container_name: joblisting-app-container
    ports:
      - "9090:9090"
    environment:
      SERVER_PORT: 9090
      MONGODB_URI: "DB url"
      MONGODB_DATABASE: "JobSeaker"
    restart: always
